### ISSUE TITLE
The thread is stuck when fetching   https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html

### ISSUE THREAD

**Issue by nateprice** [mojohaus/license-maven-plugin#399]
When I run the maven plugin it stops processing when it calls https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html java.net is down also. 

[WARNING] Unable to retrieve license from URL 'https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html' for dependency 'org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:1.0.1.Final': Certificate for <glassfish.dev.java.net> doesn't match any of the subject alternative names: [*.java.net, java.net]

The website shows

We're sorry the java.net site has closed.Most Open Source projects previously hosted on java.net have been relocated. Please contact the corresponding project administrator for relocation information.For Java related projects: http://www.oracle.com/technetwork/java/index.htmlFor Java EE-related projects: https://javaee.github.ioFor other migrated Java.net projects: https://javaee.github.io/other-migrated-projects.htmlFor FAQ please go to https://community.oracle.com/community/java/javanet-forge-sunsetFor any other questions or issues contact: java_administrator_grp@oracle.com

**Comment by nateprice** [comment]
I let it sit over night and came back to this error 

---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
	at freemarker.core.AddConcatExpression$ConcatenatedSequence.size(AddConcatExpression.java:186)
