### ISSUE TITLE
Can't build release 2.0.0 

### ISSUE THREAD

**Issue by duracotton** [mojohaus/license-maven-plugin#429]
I tried to compile the current master branch to test my fork.
But I can't even get the release 2.0.0 (commit id: bb7100581e206e1e375a0e007b7024e2688ae05a) compiled with Maven (e.g. mvn verify).

```
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 78, Failed: 3, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  download-licenses-file-names\pom.xml
[ERROR] *  download-licenses-file-names-bad-sha1-force\pom.xml
[ERROR] *  ISSUE-324\pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

...

Exception in thread "LittleProxy-JVM-shutdown-hook" java.lang.NoClassDefFoundError: io/netty/channel/group/ChannelMatchers
        at io.netty.channel.group.DefaultChannelGroup.close(DefaultChannelGroup.java:208)
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer.closeAllChannels(DefaultHttpProxyServer.java:471)
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer.doStop(DefaultHttpProxyServer.java:439)
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer.abort(DefaultHttpProxyServer.java:421)
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer$1.run(DefaultHttpProxyServer.java:148)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.group.ChannelMatchers
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 6 more
java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$409
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:86)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.proxy(GeneratedMetaMethod.java:79)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.isValidMethod(GeneratedMetaMethod.java:65)
        at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:2915)
        at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:2875)
        at groovy.lang.MetaClassImpl.getMethodWithCachingInternal(MetaClassImpl.java:1203)
        at groovy.lang.MetaClassImpl.createPogoCallCurrentSite(MetaClassImpl.java:3120)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallCurrentSite(CallSiteArray.java:108)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at KillerThread.run(LittleProxyStart.groovy:42)
Exception in thread "Thread-4" groovy.lang.GroovyRuntimeException: Failed to create DGM method proxy : java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$409
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:91)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.proxy(GeneratedMetaMethod.java:79)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.isValidMethod(GeneratedMetaMethod.java:65)
        at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:2915)
        at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:2875)
        at groovy.lang.MetaClassImpl.getMethodWithCachingInternal(MetaClassImpl.java:1203)
        at groovy.lang.MetaClassImpl.createPogoCallCurrentSite(MetaClassImpl.java:3120)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallCurrentSite(CallSiteArray.java:108)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at KillerThread.run(LittleProxyStart.groovy:42)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$409
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:86)
        ... 11 more

```

**Comment by slawekjaranowski** [comment]
Please try with the latest version

**Comment by slawekjaranowski** [comment]
if problem still exist with current code let me know.
